services:
  app:
    working_dir: /workspaces/activity-pub-relay/
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/pub-relay-prototype:cached
    environment:
      RAILS_ENV: development
      BINDING: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      REDIS_URL: "redis:6379/1"
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: '5432'
    command: sleep infinity
    ports:
      - '3000:3000'
    networks:
      - external_network
      - internal_network

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - internal_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal_network

volumes:
  postgres-data:
  redis-data:

networks:
  external_network:
  internal_network:
    internal: true
